//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileFramework.Helpers.LanguageFiles {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileFramework.Helpers.LanguageFiles.strings", typeof(strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badminton.
        /// </summary>
        internal static string Badminton {
            get {
                return ResourceManager.GetString("Badminton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballsports.
        /// </summary>
        internal static string BallSports {
            get {
                return ResourceManager.GetString("BallSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string BasketBall {
            get {
                return ResourceManager.GetString("BasketBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casualsports.
        /// </summary>
        internal static string CasualSports {
            get {
                return ResourceManager.GetString("CasualSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climbing.
        /// </summary>
        internal static string Climbing {
            get {
                return ResourceManager.GetString("Climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        internal static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing.
        /// </summary>
        internal static string Dancing {
            get {
                return ResourceManager.GetString("Dancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremesports.
        /// </summary>
        internal static string ExtremeSports {
            get {
                return ResourceManager.GetString("ExtremeSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string Fitness {
            get {
                return ResourceManager.GetString("Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football.
        /// </summary>
        internal static string FootBall {
            get {
                return ResourceManager.GetString("FootBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        internal static string Gaming {
            get {
                return ResourceManager.GetString("Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handball.
        /// </summary>
        internal static string HandBall {
            get {
                return ResourceManager.GetString("HandBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiking.
        /// </summary>
        internal static string Hiking {
            get {
                return ResourceManager.GetString("Hiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet-Ski.
        /// </summary>
        internal static string JetSki {
            get {
                return ResourceManager.GetString("JetSki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart.
        /// </summary>
        internal static string Kart {
            get {
                return ResourceManager.GetString("Kart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorbike.
        /// </summary>
        internal static string MotorBike {
            get {
                return ResourceManager.GetString("MotorBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorsports.
        /// </summary>
        internal static string MotorSports {
            get {
                return ResourceManager.GetString("MotorSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riding.
        /// </summary>
        internal static string Riding {
            get {
                return ResourceManager.GetString("Riding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rowing.
        /// </summary>
        internal static string Rowing {
            get {
                return ResourceManager.GetString("Rowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugby.
        /// </summary>
        internal static string Rugby {
            get {
                return ResourceManager.GetString("Rugby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailing.
        /// </summary>
        internal static string Sailing {
            get {
                return ResourceManager.GetString("Sailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skateboarding.
        /// </summary>
        internal static string SkateBoarding {
            get {
                return ResourceManager.GetString("SkateBoarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soccer.
        /// </summary>
        internal static string Soccer {
            get {
                return ResourceManager.GetString("Soccer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabletennis.
        /// </summary>
        internal static string TableTennis {
            get {
                return ResourceManager.GetString("TableTennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        internal static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volleyball.
        /// </summary>
        internal static string VolleyBall {
            get {
                return ResourceManager.GetString("VolleyBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakeboarding.
        /// </summary>
        internal static string WakeBoarding {
            get {
                return ResourceManager.GetString("WakeBoarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watersports.
        /// </summary>
        internal static string WaterSports {
            get {
                return ResourceManager.GetString("WaterSports", resourceCulture);
            }
        }
    }
}
